sudo: require
language: cpp

branches:
  only:
    - master

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-xenial-6.0

env:
  global:
    - CODECOV_TOKEN="e3f86b6b-0770-4816-9b7d-19b0c550229f"


cache:
  - ccache
  - apt: true
  - directories:
    - ${TRAVIS_BUILD_DIR}/build/external

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      addons: &gcc7
        apt:
          sources: *all_sources
          packages:
            - g++-7
            - lcov
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && COVERAGE=Off && BUILD_TOOLS=On"
    - os: linux
      dist: xenial
      compiler: gcc
      addons: &gcc7
        apt:
          sources: *all_sources
          packages: ['g++-7']
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && PISA_COMPILE_HEADERS=On && BUILD_TOOLS=On"
    - os: linux
      dist: xenial
      compiler: gcc
      addons: &gcc8
        apt:
          sources: *all_sources
          packages: ['g++-8']
      env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && COVERAGE=Off && DOCKER=On && BUILD_TOOLS=On"
    - os: linux
      dist: xenial
      compiler: clang
      addons:
          apt:
              sources: *all_sources
              packages: ['clang-5.0', 'libstdc++-7-dev']
      env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && COVERAGE=Off && BUILD_TOOLS=On"
    - os: linux
      dist: xenial
      compiler: clang
      addons:
          apt:
              sources: *all_sources
              packages: ['clang-6.0', 'libstdc++-7-dev']
      env: MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0 && COVERAGE=Off && BUILD_TOOLS=On"
    - os: linux
      dist: xenial
      compiler: clang
      addons:
          apt:
              sources: *all_sources
              packages: ['clang-6.0', 'libstdc++-7-dev']
      env: MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0 && COVERAGE=On && BUILD_TOOLS=Off"
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      env: MATRIX_EVAL="CC=clang && CXX=clang++ && COVERAGE=Off && BUILD_TOOLS=On"

# Install dependencies
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install ccache;
      export PATH="/usr/local/opt/ccache/libexec:$PATH";
    fi
  - eval "${MATRIX_EVAL}"

script:
    - cd build
    - travis_wait 50 sleep 3000
    - cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=${COVERAGE} -DPISA_COMPILE_HEADERS=${PISA_COMPILE_HEADERS} ${CMAKE_OPTIONS} -DPISA_BUILD_TOOLS=${BUILD_TOOLS} ..
    - if [[ "$PISA_COMPILE_HEADERS" != "On" ]]; then
        make;
        ctest -j2;
      fi

after_success:
  - |-
    if [[ "${COVERAGE}" == "On" ]]; then
      bash <(curl -s https://codecov.io/bash);
    fi
  - |-
    if [[ "$TRAVIS_BRANCH" == "master" && "${DOCKER}" == "On" ]]; then
      curl -s -X POST \
      -H "Content-Type:application/json" \
      -H "Travis-API-Version:3" \
      -H "Accept:application/json" \
      -H "Authorization:token ${TRAVIS_API_TOKEN}" \
      -d '{"request":{"branch":"master"}}' \
      'https://api.travis-ci.com/repo/pisa-engine%2Fdocker/requests'
    fi

